### ISSUE TITLE
npm ERR! Could not install from "" as it does not contain a package.json file.

### ISSUE THREAD

**Issue by fabianhenzler** [riyadhalnur/npm-modules-sync#58]
* node version: 9.5.1
* npm version: 5.7.1

### Error output
```
 ➜  ~ npm-sync init -t XXX -i XXX     
 ✔ Writing configuration to disk
 ❯ Fetching information from GitHub
   ✔ Get list of packages from GitHub
   ✖ Install npm packages globally
TypeError: Cannot create property 'context' on string 'npm ERR! code ENOLOCAL
npm ERR! Could not install from "" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fabianhenzler/.npm/_logs/2018-02-27T09_05_06_299Z-debug.log
'
    at tasks.then.catch.err (/usr/local/lib/node_modules/npm-modules-sync/node_modules/listr/index.js:74:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

**Comment by riyadhalnur** [comment]
Could you also paste the output of `/Users/fabianhenzler/.npm/_logs/2018-02-27T09_05_06_299Z-debug.log`?

**Comment by fabianhenzler** [comment]
Sorry, deleted the whole .npm folder when re-installing node. 
The issue was that no global npm package was installed except `npm-modules-sync`

**Comment by riyadhalnur** [comment]
Ah, right. Yes, on first setup, it tries to back up all your installed packages. Glad the issue is resolved.
